services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      #- ./pg_data:/var/lib/postgresql/data:rw

  minio:
    image: quay.io/minio/minio
    #volumes:
      #- ./minio_data:/data:rw
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    command: server /data --console-address ":9001"

  api:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
    - postgres
    - minio
    ports:
      - 8080:8080
    #command: production
